version: '3'
services:
  db:
    image: mongo:latest
  web:
    build: .
    environment:
      - DATABASE_URL=db
    volumes:
      - .:/app
    ports:
      - "9292:9292"
    depends_on:
      - db
