---
version: '3.3'
services:
  post_db:
    image: mongo:${DB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - net_back
  ui:
    build: ./ui
    image: ${USERNAME}-ui
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - net_front
  post:
    build: ./post-py
    image: ${USERNAME}-post
    networks:
      - net_front
      - net_back
  comment:
    build: ./comment
    image: ${USERNAME}-comment
    networks:
      - net_front
      - net_back
  prometheus:
    image: ${USERNAME}-prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - net_front
      - net_back
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - net_front
      - net_back
volumes:
  prometheus_data:
  post_db:
networks:
  net_front:
    ipam:
      driver: ${NET_DRIVER}
      config:
        - subnet: ${NET_FRONT}
  net_back:
    ipam:
      driver: ${NET_DRIVER}
      config:
        - subnet: ${NET_BACK}
