---
version: '3.3'
services:
  post_db:
    image: mongo:${DB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - ${NET_BACK}
        aliases:
          - post_db
          - comment_db
  ui:
    container_name: ui
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${UI_PORT}:9292/tcp
    networks:
      - ${NET_FRONT}
  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - ${NET_FRONT}
      - ${NET_BACK}
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - ${NET_FRONT}
      - ${NET_BACK}
  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command: # Передаем доп параметры в командной строке
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d' # Задаем время хранения метрик в 1 день
    networks:
      - ${NET_FRONT}
      - ${NET_BACK}
  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      - ${NET_FRONT}
      - ${NET_BACK}
volumes:
  prometheus_data:
  post_db:
networks:
  net_front:
  net_back:
