---
#  multi-net parametrical config

version: '3.3'
services:
  post_db:
    image: ${DB_VERSION}
    volumes:
      - post_db:/data/db
    networks:
      - net_back
  ui:
    build: ./ui
    image: ${USERNAME}/${}
    ports:
      - ${UI_PORT}
    networks:
      - net_front
  post:
    build: ./post-py
    image: ${USERNAME}/${POST_VERSION}
    networks:
      - net_front
      - net_back
  comment:
    build: ./comment
    image: ${USERNAME}/${COMMENT_VERSION}
    networks:
      - net_front
      - net_back

volumes:
  post_db:

networks:
  net_front:
    ipam:
      driver: ${NET_DRIVER}
      config:
        - subnet: ${NET_FRONT}
  net_back:
    ipam:
      driver: ${NET_DRIVER}
      config:
        - subnet: ${NET_BACK}
